[project]
name = "adaptive-bip"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.grid-node-manager]
path = "contracts/grid-node-manager.clar"
depends_on = []

[contracts.consumption-tracker]
path = "contracts/consumption-tracker.clar"
depends_on = []

[contracts.energy-credit-token]
path = "contracts/energy-credit-token.clar"
depends_on = []

[contracts.decentralized-energy-exchange]
path = "contracts/decentralized-energy-exchange.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
